[build]
  command = "npm run build" # Specify the build command if needed
  publish = "public" # Specify the directory to publish

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
