[build]
command = "npm run build"  # Replace with your actual build command
publish = "build"          # Replace with your actual build directory

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
